version: '3.4'

services:
  jenkins-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}jenkins-test
    container_name: jenkins-test
    user: root
    restart: on-failure
    ports:
      - "1234:8080"
      - "4321:50000"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      K-Net:
      
networks:
  K-Net:
    name: K-Net
    driver: bridge